package tasks

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestMyStrToInt(t *testing.T) {
	assert := assert.New(t)
	num, err := MyStrToInt("-1")
	assert.Equal(-1, num)
	num, _ = MyStrToInt("7788")
	assert.Equal(7788, num)
	num, _ = MyStrToInt("0000000000000")
	assert.Equal(0, num)
	num, _ = MyStrToInt("00000000000003506")
	assert.Equal(3506, num)
	num, _ = MyStrToInt("+1")
	assert.Equal(1, num)

	_, err = MyStrToInt("++1")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt("  1")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt("1  ")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt("1.0")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt("1,0")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt("--1")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt("9223372036854775808")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt("-9223372036854775809")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt("")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt(" ")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt(" sdasd asdflsf;g")
	assert.NotEqual(nil, err)
}

func TestMyStrToInt2(t *testing.T) {
	assert := assert.New(t)
	num, err := MyStrToInt2("-1")
	assert.Equal(-1, num)
	num, _ = MyStrToInt2("7788")
	assert.Equal(7788, num)
	num, _ = MyStrToInt2("0000000000000")
	assert.Equal(0, num)
	num, _ = MyStrToInt2("00000000000003506")
	assert.Equal(3506, num)
	num, _ = MyStrToInt2("+1")
	assert.Equal(1, num)

	_, err = MyStrToInt2("++1")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2("  1")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2("1  ")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2("1.0")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2("1,0")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2("--1")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2("9223372036854775808")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2("-9223372036854775809")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2("")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2(" ")
	assert.NotEqual(nil, err)
	_, err = MyStrToInt2(" sdasd asdflsf;g")
	assert.NotEqual(nil, err)
}
